// Auto-generated — do not edit manually
// Regenerated whenever courses.js is updated

const COURSES = [
  {"name": "Quarry Oaks Golf Club", "city": "Ashland", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$55–$95", "phone": "(402) 944-6000", "website": "https://quarryoaks.com/", "description": "Nebraska's most dramatic public layout — carved from limestone bluffs above the Platte River. Jon LaFoy's masterpiece rewards bold shot-making from every tee.", "photo": "https://www.nebgolf.org/wp-content/uploads/2019/02/QuarryOaks2b-1000x660.jpg", "social_facebook": "https://www.facebook.com/QuarryOaksGolf/", "slug": "quarry-oaks-golf-club"},
  {"name": "Wilderness Ridge Golf Club", "city": "Lincoln", "region": "East", "club_type": "Private", "holes": "27", "greens_fee": "Members only", "phone": "(402) 434-5106", "website": "https://www.wildernessridgegolf.com/", "description": "Lincoln's premier private club with 27 holes of dramatic, wooded terrain. Impeccable conditioning and an exclusive atmosphere.", "photo": "", "social_facebook": "", "slug": "wilderness-ridge-golf-club"},
  {"name": "Ashland Golf Club", "city": "Ashland", "region": "East", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$18–$28", "phone": "(402) 944-3133", "website": "", "description": "A friendly 9-hole semi-private layout in the heart of Ashland — a great option before or after visiting Mahoney State Park.", "photo": "", "social_facebook": "https://www.facebook.com/AshlandGolfClub/", "slug": "ashland-golf-club"},
  {"name": "Bay Hills Golf Club", "city": "Bellevue", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$25–$40", "phone": "(402) 292-9300", "website": "", "description": "A scenic public layout in Bellevue offering parkland-style golf with tree-lined fairways and natural water features.", "photo": "", "social_facebook": "https://www.facebook.com/BayHillsGolfClub/", "slug": "bay-hills-golf-club"},
  {"name": "Benson Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 444-4626", "website": "", "description": "A classic Omaha municipal track with a loyal following and affordable daily fees — a go-to for northside golfers.", "photo": "", "social_facebook": "https://www.facebook.com/OmahaParksRec/", "slug": "benson-golf-course"},
  {"name": "Champions Run", "city": "Omaha", "region": "East", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$45–$70", "phone": "(402) 898-0888", "website": "https://www.championsrungolf.com/", "description": "One of Omaha's premier semi-private tracks with lush fairways, challenging bunkering, and a full practice facility.", "photo": "", "social_facebook": "https://www.facebook.com/ChampionsRunGolf/", "slug": "champions-run"},
  {"name": "Country Drive Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 493-1515", "website": "", "description": "A pleasant 9-hole public course in northwest Omaha — great for beginners and quick rounds.", "photo": "", "social_facebook": "", "slug": "country-drive-golf-course"},
  {"name": "Crooked Creek Golf Club", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$30–$45", "phone": "(402) 742-7600", "website": "", "description": "A newer public track on Lincoln's northwest edge with wide fairways, multiple tee options, and a welcoming attitude toward golfers of all skill levels.", "photo": "", "social_facebook": "https://www.facebook.com/CrookedCreekGolfLincoln/", "slug": "crooked-creek-golf-club"},
  {"name": "David City Golf Course", "city": "David City", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 367-3572", "website": "", "description": "A classic small-town 9-hole layout serving the David City community with great value and friendly play.", "photo": "", "social_facebook": "", "slug": "david-city-golf-course"},
  {"name": "Eagle Hills Golf Course", "city": "Eagle", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$20–$35", "phone": "(402) 781-2244", "website": "", "description": "A friendly and affordable daily-fee course just minutes from Lincoln offering solid parkland-style golf in a relaxed setting.", "photo": "", "social_facebook": "https://www.facebook.com/EagleHillsGolf/", "slug": "eagle-hills-golf-course"},
  {"name": "Elks Country Club - Columbus", "city": "Columbus", "region": "East", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$25–$40", "phone": "(402) 563-1030", "website": "", "description": "A well-established Columbus semi-private club with a solid layout and active membership community.", "photo": "", "social_facebook": "", "slug": "elks-country-club---columbus"},
  {"name": "Elmwood Park Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(402) 444-4656", "website": "", "description": "One of Omaha's oldest public courses, nestled in the historic Elmwood Park neighborhood — a true city classic.", "photo": "", "social_facebook": "", "slug": "elmwood-park-golf-course"},
  {"name": "Field Club of Omaha", "city": "Omaha", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 344-8010", "website": "https://www.fieldclubomaha.com/", "description": "An 18-hole private golf course in Omaha, East Nebraska.", "photo": "", "social_facebook": "", "slug": "field-club-of-omaha"},
  {"name": "Firethorn Golf Club", "city": "Lincoln", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 489-1905", "website": "https://firehorngolf.com/", "description": "Lincoln's most exclusive private club, set on rolling terrain with mature trees and meticulously conditioned fairways and greens.", "photo": "", "social_facebook": "", "slug": "firethorn-golf-club"},
  {"name": "Fremont Golf Club", "city": "Fremont", "region": "East", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$28–$42", "phone": "(402) 721-0890", "website": "", "description": "A semi-private Fremont club with a challenging championship layout and one of Eastern Nebraska's best practice facilities.", "photo": "", "social_facebook": "https://www.facebook.com/FremontGolfClub/", "slug": "fremont-golf-club"},
  {"name": "Happy Hollow Club", "city": "Omaha", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 551-2490", "website": "https://www.happyhollowclub.com/", "description": "An 18-hole private golf course in Omaha, East Nebraska.", "photo": "", "social_facebook": "", "slug": "happy-hollow-club"},
  {"name": "Hidden Valley Golf Club", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$26–$42", "phone": "(402) 895-4520", "website": "", "description": "Tucked into southwest Omaha, Hidden Valley offers a scenic escape with rolling fairways and reliable conditions.", "photo": "", "social_facebook": "", "slug": "hidden-valley-golf-club"},
  {"name": "Highlands Golf Course", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$34", "phone": "(402) 441-6026", "website": "https://lincolncitygolf.org/highlands/", "description": "A shorter, friendlier layout on Lincoln's northwest side. Perfect for beginners and mid-handicappers who want a relaxed round without sacrificing scenery.", "photo": "", "social_facebook": "https://www.facebook.com/LincolnCityGolf/", "slug": "highlands-golf-course"},
  {"name": "Hillcrest Country Club", "city": "Lincoln", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 466-2400", "website": "", "description": "An established Lincoln private club with a classic parkland layout and one of the city's most storied championship histories.", "photo": "", "social_facebook": "", "slug": "hillcrest-country-club"},
  {"name": "Hilltop Country Club", "city": "Omaha", "region": "East", "club_type": "Private", "holes": "9", "greens_fee": "Members only", "phone": "(402) 558-7820", "website": "", "description": "A private 9-hole course in Omaha offering a friendly round in East Nebraska.", "photo": "", "social_facebook": "", "slug": "hilltop-country-club"},
  {"name": "Holmes Golf Course", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$28–$42", "phone": "(402) 441-8960", "website": "https://lincolncitygolf.org/holmes/", "description": "Draped over two rolling hills at the southern tip of Holmes Lake, this beloved Lincoln municipal course delivers sweeping Capitol views and water drama on nearly every back-nine hole. The broad, gently undulating greens and tree-lined fairways reward smart shot-making.", "photo": "https://www.lincoln.ne.gov/files/sharedassets/public/v/1/parks-and-recreation/golf/holmes-golf-course-2-copy.jpg", "social_facebook": "https://www.facebook.com/LincolnCityGolf/", "slug": "holmes-golf-course"},
  {"name": "Iron Horse Golf Club", "city": "Ashland", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$25–$40", "phone": "(402) 944-3655", "website": "", "description": "A well-regarded daily-fee layout near Ashland with challenging terrain and a great practice facility.", "photo": "", "social_facebook": "https://www.facebook.com/IronHorseGolfAshland/", "slug": "iron-horse-golf-club"},
  {"name": "Jim Ager Golf Course", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$8–$12", "phone": "(402) 441-8960", "website": "https://lincolncitygolf.org/", "description": "A compact par-3 course next to Holmes Golf Course, purpose-built for juniors and beginners. Low pressure, low cost, and a great first step into the game.", "photo": "", "social_facebook": "", "slug": "jim-ager-golf-course"},
  {"name": "Johnny Goodman Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(402) 444-4626", "website": "", "description": "Named for Omaha's legendary amateur champion, this south Omaha municipal track is a historic and affordable round.", "photo": "", "social_facebook": "", "slug": "johnny-goodman-golf-course"},
  {"name": "Knolls Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$24–$38", "phone": "(402) 444-4656", "website": "", "description": "Rolling terrain and tight tree-lined fairways make Knolls a genuine challenge for Omaha's mid-handicappers.", "photo": "", "social_facebook": "https://www.facebook.com/OmahaParksRec/", "slug": "knolls-golf-course"},
  {"name": "Lake Ridge Golf Course", "city": "Blair", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 426-2028", "website": "", "description": "Blair's signature public course with river bluff views and a layout that challenges golfers of all abilities.", "photo": "", "social_facebook": "", "slug": "lake-ridge-golf-course"},
  {"name": "Lost Rail Golf Club", "city": "Milford", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(402) 761-3600", "website": "", "description": "A charming rural course west of Lincoln with a loyal local following and scenic prairie surroundings.", "photo": "", "social_facebook": "https://www.facebook.com/LostRailGolf/", "slug": "lost-rail-golf-club"},
  {"name": "Mahoney Golf Course", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$26–$40", "phone": "(402) 441-8969", "website": "https://lincolncitygolf.org/mahoney/", "description": "Set within Mahoney State Park, this scenic public course offers ponds, wooded edges, and wildlife around every turn.", "photo": "", "social_facebook": "https://www.facebook.com/LincolnCityGolf/", "slug": "mahoney-golf-course"},
  {"name": "Miracle Hill Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(402) 498-0220", "website": "", "description": "An north Omaha public course with a mix of challenging and forgiving holes, popular for league and casual play.", "photo": "", "social_facebook": "https://www.facebook.com/MiracleHillGolf/", "slug": "miracle-hill-golf-course"},
  {"name": "North Bend Golf Course", "city": "North Bend", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 652-8521", "website": "", "description": "A charming 9-hole country course in North Bend with a relaxed pace and affordable fees.", "photo": "", "social_facebook": "", "slug": "north-bend-golf-course"},
  {"name": "NuMark Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 444-4656", "website": "", "description": "One of Omaha's municipal 9-hole courses offering affordable golf on the south side of the city.", "photo": "", "social_facebook": "", "slug": "numark-golf-course"},
  {"name": "Oak Hills Country Club", "city": "Omaha", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 291-0909", "website": "", "description": "An 18-hole private golf course in Omaha, East Nebraska.", "photo": "", "social_facebook": "", "slug": "oak-hills-country-club"},
  {"name": "Omaha Country Club", "city": "Omaha", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 556-0620", "website": "https://www.omahacc.com/", "description": "An 18-hole private golf course in Omaha, East Nebraska.", "photo": "", "social_facebook": "", "slug": "omaha-country-club"},
  {"name": "Pacific Springs Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$28–$48", "phone": "(402) 691-1600", "website": "", "description": "A well-maintained daily-fee course in west Omaha offering good value and challenging play for all skill levels.", "photo": "", "social_facebook": "https://www.facebook.com/PacificSpringsGolf/", "slug": "pacific-springs-golf-course"},
  {"name": "Pioneers Golf Course", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$25–$38", "phone": "(402) 441-8966", "website": "https://lincolncitygolf.org/pioneers/", "description": "A classic tree-lined municipal track with a reputation for firm, fast greens set among mature elms and oaks just minutes from downtown Lincoln.", "photo": "", "social_facebook": "https://www.facebook.com/LincolnCityGolf/", "slug": "pioneers-golf-course"},
  {"name": "Platteview Golf Club", "city": "Springfield", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$25–$38", "phone": "(402) 253-2554", "website": "", "description": "A south metro public course with Platte River valley views and a challenging layout that rewards accurate iron play.", "photo": "", "social_facebook": "https://www.facebook.com/PlatteviewGolf/", "slug": "platteview-golf-club"},
  {"name": "Quail Run Golf Course", "city": "Columbus", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(402) 564-1313", "website": "", "description": "Columbus's premier public layout offering a well-balanced test of golf with consistent conditioning.", "photo": "", "social_facebook": "https://www.facebook.com/QuailRunGolfColumbus/", "slug": "quail-run-golf-course"},
  {"name": "River Wilds Golf Course", "city": "Valley", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$28–$44", "phone": "(402) 359-9051", "website": "", "description": "A Valley gem along the Platte River corridor with natural wetlands, mature trees, and a memorable layout.", "photo": "", "social_facebook": "https://www.facebook.com/RiverWildsGolf/", "slug": "river-wilds-golf-course"},
  {"name": "Schuyler Golf Club", "city": "Schuyler", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 352-5503", "website": "", "description": "A well-maintained 9-hole public course in Schuyler offering great value and a welcoming atmosphere.", "photo": "", "social_facebook": "", "slug": "schuyler-golf-club"},
  {"name": "Seward Community Golf Course", "city": "Seward", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 643-4272", "website": "", "description": "Seward's beloved 9-hole community course — a cornerstone of the local golf scene for generations.", "photo": "", "social_facebook": "", "slug": "seward-community-golf-course"},
  {"name": "Shadow Ridge Country Club", "city": "Omaha", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 895-7300", "website": "https://www.shadowridgegolf.com/", "description": "An 18-hole private golf course in Omaha, East Nebraska.", "photo": "", "social_facebook": "", "slug": "shadow-ridge-country-club"},
  {"name": "Shoreline Golf Course", "city": "Carter Lake", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$26–$42", "phone": "(712) 347-5173", "website": "", "description": "Situated right on the Iowa/Nebraska border, Shoreline offers outstanding Missouri River views and a memorable layout.", "photo": "", "social_facebook": "", "slug": "shoreline-golf-course"},
  {"name": "Spring Lake Golf Course", "city": "Papillion", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$28–$44", "phone": "(402) 339-3633", "website": "", "description": "A scenic Papillion layout with lake views and well-manicured conditions — one of the metro area's best public values.", "photo": "", "social_facebook": "https://www.facebook.com/SpringLakeGolfPapillion/", "slug": "spring-lake-golf-course"},
  {"name": "Steve Hogan Golf Course", "city": "Council Bluffs", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(712) 328-5208", "website": "", "description": "Council Bluffs' primary public municipal course, just across the river from Omaha. A well-maintained layout with affordable fees.", "photo": "", "social_facebook": "", "slug": "steve-hogan-golf-course"},
  {"name": "Stone Creek Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$30–$50", "phone": "(402) 895-3300", "website": "https://www.stonecreekgolfomaha.com/", "description": "A popular south Omaha daily-fee course with well-maintained conditions and a fair test for all skill levels.", "photo": "", "social_facebook": "https://www.facebook.com/StoneCreekGolf/", "slug": "stone-creek-golf-course"},
  {"name": "Tara Hills Golf Course", "city": "Papillion", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$15–$24", "phone": "(402) 331-2300", "website": "", "description": "A well-maintained 9-hole public course in Papillion — ideal for a quick round or an evening nine.", "photo": "", "social_facebook": "", "slug": "tara-hills-golf-course"},
  {"name": "The Club at Indian Creek", "city": "Elkhorn", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 289-0900", "website": "https://www.theindiacreekclub.com/", "description": "An 18-hole private golf course in Elkhorn, East Nebraska.", "photo": "", "social_facebook": "", "slug": "the-club-at-indian-creek"},
  {"name": "The Country Club of Lincoln", "city": "Lincoln", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 477-0880", "website": "", "description": "Lincoln's oldest and most prestigious private club, founded in 1905. A historic layout with impeccable conditioning and deep ties to Nebraska golf heritage.", "photo": "", "social_facebook": "", "slug": "the-country-club-of-lincoln"},
  {"name": "The Fairways at Lincoln", "city": "Lincoln", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(402) 466-3336", "website": "", "description": "An approachable daily-fee course on Lincoln's east side with a relaxed pace and friendly staff. Great value for a quick weekday round.", "photo": "", "social_facebook": "", "slug": "the-fairways-at-lincoln"},
  {"name": "The Pines Country Club", "city": "Valley", "region": "East", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 359-5900", "website": "", "description": "An 18-hole private golf course in Valley, East Nebraska.", "photo": "", "social_facebook": "", "slug": "the-pines-country-club"},
  {"name": "The Players Club", "city": "Omaha", "region": "East", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$45–$75", "phone": "(402) 895-4466", "website": "https://www.playersclubomaha.com/", "description": "Southwest Omaha's premium semi-private experience with tournament-quality conditioning and a prestigious atmosphere.", "photo": "", "social_facebook": "", "slug": "the-players-club"},
  {"name": "Tiburon Golf Club", "city": "Omaha", "region": "East", "club_type": "Semi-Private", "holes": "27", "greens_fee": "$40–$65", "phone": "(402) 895-2688", "website": "https://www.tiburongolf.com/", "description": "Three nines of championship golf in southwest Omaha. Water features, elevated greens, and tight fairways demand precision from tee to green.", "photo": "", "social_facebook": "https://www.facebook.com/TiburonGolfOmaha/", "slug": "tiburon-golf-club"},
  {"name": "Tregaron Golf Club", "city": "Crete", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 826-2255", "website": "", "description": "An underrated gem south of Lincoln offering solid value and well-maintained parkland-style golf in a relaxed setting.", "photo": "", "social_facebook": "", "slug": "tregaron-golf-club"},
  {"name": "Valley View Golf Course", "city": "Wahoo", "region": "East", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 443-4256", "website": "", "description": "Wahoo's community 9-hole course with valley views and an easygoing atmosphere.", "photo": "", "social_facebook": "", "slug": "valley-view-golf-course"},
  {"name": "Warren Swigart Golf Course", "city": "Gretna", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(402) 332-4440", "website": "", "description": "Gretna's favorite public layout with well-maintained fairways and an easy-going atmosphere for all skill levels.", "photo": "", "social_facebook": "https://www.facebook.com/WarrenSwigartGolf/", "slug": "warren-swigart-golf-course"},
  {"name": "Westwood Golf Course", "city": "Omaha", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$24–$38", "phone": "(402) 453-3000", "website": "", "description": "A solid northwest Omaha daily-fee course with consistent conditioning and fair greens fees.", "photo": "", "social_facebook": "https://www.facebook.com/WestwoodGolfOmaha/", "slug": "westwood-golf-course"},
  {"name": "Whispering Woods Golf Club", "city": "Papillion", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$32–$52", "phone": "(402) 537-3000", "website": "https://whisperingwoodsgolf.com/", "description": "One of Papillion's top public layouts with tree-lined fairways and consistent conditioning that keeps golfers coming back.", "photo": "", "social_facebook": "https://www.facebook.com/WhisperingWoodsGolf/", "slug": "whispering-woods-golf-club"},
  {"name": "Whitetail Run Golf Course", "city": "Pilger", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$18–$30", "phone": "(402) 368-5474", "website": "", "description": "A hidden gem in Pilger with a scenic prairie layout and surprisingly challenging holes.", "photo": "", "social_facebook": "", "slug": "whitetail-run-golf-course"},
  {"name": "Willow Lakes Golf Course", "city": "Fremont", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$24–$38", "phone": "(402) 727-4653", "website": "", "description": "A picturesque Fremont public layout built around natural lakes and wetlands — a scenic and affordable round.", "photo": "", "social_facebook": "https://www.facebook.com/WillowLakesGolf/", "slug": "willow-lakes-golf-course"},
  {"name": "Woodland Hills Golf Course", "city": "Eagle", "region": "East", "club_type": "Public", "holes": "18", "greens_fee": "$22–$38", "phone": "(402) 781-2466", "website": "", "description": "Rolling terrain and mature trees define this Eagle gem — a well-kept daily-fee layout that punches above its price point.", "photo": "", "social_facebook": "https://www.facebook.com/WoodlandHillsGolfEagle/", "slug": "woodland-hills-golf-course"},
  {"name": "Atkinson Stuart Country Club", "city": "Atkinson", "region": "North Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 925-5350", "website": "", "description": "A friendly 9-hole semi-private course in Atkinson — quiet, well-tended, and a genuine slice of Nebraska small-town golf.", "photo": "", "social_facebook": "", "slug": "atkinson-stuart-country-club"},
  {"name": "Bassett Country Club", "city": "Bassett", "region": "North Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 684-3677", "website": "", "description": "A 9-hole semi-private layout in Bassett offering a relaxed round on the eastern edge of the Sandhills.", "photo": "", "social_facebook": "", "slug": "bassett-country-club"},
  {"name": "O'Neill Golf Club", "city": "O'Neill", "region": "North Central", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$20–$30", "phone": "(402) 336-3368", "website": "", "description": "North Central Nebraska's best 18-hole layout — a welcoming semi-private track in the heart of the Holt County seat.", "photo": "", "social_facebook": "", "slug": "oneill-golf-club"},
  {"name": "Ord Golf Club", "city": "Ord", "region": "North Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 728-3077", "website": "", "description": "A 9-hole semi-private layout in Ord — small-town golf at its most charming in the heart of the Loup River valley.", "photo": "", "social_facebook": "", "slug": "ord-golf-club"},
  {"name": "Summerland Golf Club", "city": "Ewing", "region": "North Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 685-4282", "website": "", "description": "Nebraska's most remote 9-hole public course — a true off-the-beaten-path golf experience in Ewing.", "photo": "", "social_facebook": "", "slug": "summerland-golf-club"},
  {"name": "Albion Country Club", "city": "Albion", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 395-6161", "website": "", "description": "A classic 9-hole semi-private country club in Albion with a loyal local membership and well-kept conditions.", "photo": "", "social_facebook": "", "slug": "albion-country-club"},
  {"name": "Antelope Country Club", "city": "Neligh", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 887-4433", "website": "", "description": "Neligh's 9-hole country club offering a quiet, friendly round in Northeast Nebraska's rolling terrain.", "photo": "", "social_facebook": "", "slug": "antelope-country-club"},
  {"name": "Cedar View Country Club", "city": "Laurel", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 256-3249", "website": "", "description": "A 9-hole semi-private course in Laurel with tree-lined fairways and a welcoming small-town atmosphere.", "photo": "", "social_facebook": "", "slug": "cedar-view-country-club"},
  {"name": "Club 91 Golf Course", "city": "South Sioux City", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(402) 494-0440", "website": "", "description": "A solid 18-hole public course in South Sioux City with good conditions and a fair test for all skill levels.", "photo": "", "social_facebook": "", "slug": "club-91-golf-course"},
  {"name": "Covington Links Golf Course", "city": "South Sioux City", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(402) 494-1813", "website": "", "description": "Missouri River views and challenging links-style holes make Covington Links one of Northeast Nebraska's best kept secrets.", "photo": "", "social_facebook": "https://www.facebook.com/CovingtonLinksGolf/", "slug": "covington-links-golf-course"},
  {"name": "Crofton Lakeview Golf Course", "city": "Crofton", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$18–$30", "phone": "(402) 388-4625", "website": "", "description": "A scenic 18-hole public course in Crofton with Lewis and Clark Lake views and a peaceful Northeastern Nebraska setting.", "photo": "", "social_facebook": "https://www.facebook.com/CroftonLakeview/", "slug": "crofton-lakeview-golf-course"},
  {"name": "Eldorado Hills Golf Club", "city": "Norfolk", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(402) 371-0350", "website": "", "description": "A solid daily-fee option in Norfolk offering good value and a well-maintained parkland layout.", "photo": "", "social_facebook": "https://www.facebook.com/EldoradoHillsGolf/", "slug": "eldorado-hills-golf-club"},
  {"name": "Elkhorn Acres Golf Course", "city": "Madison", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$18–$30", "phone": "(402) 454-2381", "website": "", "description": "An 18-hole public layout in Madison offering a full round of golf at an affordable price.", "photo": "", "social_facebook": "", "slug": "elkhorn-acres-golf-course"},
  {"name": "Elkhorn Valley Golf Club", "city": "Tilden", "region": "Northeast", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$18–$30", "phone": "(402) 368-5474", "website": "", "description": "A charming semi-private 18-hole layout in Tilden along the Elkhorn River valley.", "photo": "", "social_facebook": "", "slug": "elkhorn-valley-golf-club"},
  {"name": "Evergreen Hills Golf Course", "city": "Niobrara", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 857-3435", "website": "", "description": "A scenic 9-hole public course in Niobrara with views of the Missouri River valley and a peaceful, natural setting.", "photo": "", "social_facebook": "", "slug": "evergreen-hills-golf-course"},
  {"name": "Fair Play Golf Course", "city": "Battle Creek", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 675-2273", "website": "", "description": "Battle Creek's community 9-hole course — approachable, affordable, and a staple of local golf culture.", "photo": "", "social_facebook": "", "slug": "fair-play-golf-course"},
  {"name": "Hartington Golf Club", "city": "Hartington", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 254-6700", "website": "", "description": "A 9-hole semi-private layout in Hartington that's been a cornerstone of the Cedar County golf community for decades.", "photo": "", "social_facebook": "", "slug": "hartington-golf-club"},
  {"name": "Highland Oaks Golf Club", "city": "Randolph", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 337-0324", "website": "", "description": "A peaceful 9-hole public course in Randolph tucked among oak-covered hills in Northeast Nebraska.", "photo": "", "social_facebook": "", "slug": "highland-oaks-golf-club"},
  {"name": "Indian Trails Country Club", "city": "Beemer", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 528-3495", "website": "", "description": "A well-maintained 9-hole semi-private course in Beemer offering a friendly round for members and guests.", "photo": "", "social_facebook": "", "slug": "indian-trails-country-club"},
  {"name": "Landmand Golf Club", "city": "Homer", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$60–$100", "phone": "(402) 698-2100", "website": "https://www.landmandgolfclub.com/", "description": "Nebraska's newest standout public course — a links-style layout in the Missouri River valley with dramatic terrain and world-class ambitions.", "photo": "https://www.nebgolf.org/wp-content/uploads/2022/01/Landmand-Aerial-1000x660.jpg", "social_facebook": "https://www.facebook.com/LandmandGolfClub/", "slug": "landmand-golf-club"},
  {"name": "Logan Valley Golf Course", "city": "Tekamah", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 374-2911", "website": "", "description": "A 9-hole public layout in Tekamah along the Logan Creek valley — scenic, affordable, and uncrowded.", "photo": "", "social_facebook": "", "slug": "logan-valley-golf-course"},
  {"name": "Norfolk Country Club", "city": "Norfolk", "region": "Northeast", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 371-0700", "website": "", "description": "Norfolk's premier private club with a championship 18-hole layout and a long tradition of hosting top regional events.", "photo": "", "social_facebook": "", "slug": "norfolk-country-club"},
  {"name": "Northridge Country Club", "city": "Norfolk", "region": "Northeast", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$25–$40", "phone": "(402) 371-6601", "website": "", "description": "Norfolk's premier semi-private layout with excellent conditioning and a welcoming atmosphere for members and guests.", "photo": "", "social_facebook": "", "slug": "northridge-country-club"},
  {"name": "Oakland Golf Club", "city": "Oakland", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 685-5808", "website": "", "description": "A 9-hole semi-private course in Oakland that's been the heart of Burt County golf for generations.", "photo": "", "social_facebook": "", "slug": "oakland-golf-club"},
  {"name": "Old Dane Golf Club", "city": "Wausa", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 586-2276", "website": "", "description": "A charming 9-hole course in Wausa — one of the smallest and most authentic golf experiences in Nebraska.", "photo": "", "social_facebook": "", "slug": "old-dane-golf-club"},
  {"name": "Pierce Community Golf Course", "city": "Pierce", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 329-6412", "website": "", "description": "Pierce's 9-hole community course, maintaining an affordable and accessible golf option for the local area.", "photo": "", "social_facebook": "", "slug": "pierce-community-golf-course"},
  {"name": "Plainview Country Club", "city": "Plainview", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 582-4646", "website": "", "description": "A 9-hole semi-private layout in Plainview serving the Pierce County golf community with a welcoming atmosphere.", "photo": "", "social_facebook": "", "slug": "plainview-country-club"},
  {"name": "Randolph Community Golf Course", "city": "Randolph", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 337-0324", "website": "", "description": "Randolph's 9-hole community golf course — a relaxed, affordable option in the heart of Cedar County.", "photo": "", "social_facebook": "", "slug": "randolph-community-golf-course"},
  {"name": "Rolling Hills Country Club", "city": "Pender", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 385-3046", "website": "", "description": "A 9-hole semi-private course in Pender with rolling terrain that lives up to its name.", "photo": "", "social_facebook": "", "slug": "rolling-hills-country-club"},
  {"name": "Tatanka Golf Club", "city": "Stanton", "region": "Northeast", "club_type": "Public", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 439-2600", "website": "", "description": "A modern 18-hole public layout in Stanton delivering more challenge and scenery than you'd expect from a rural Nebraska course.", "photo": "", "social_facebook": "https://www.facebook.com/TatankaGolfClub/", "slug": "tatanka-golf-club"},
  {"name": "Taylor Creek Golf Course", "city": "Fullerton", "region": "Northeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 536-2402", "website": "", "description": "A 9-hole public course in Fullerton following Taylor Creek through central Nance County.", "photo": "", "social_facebook": "", "slug": "taylor-creek-golf-course"},
  {"name": "Twin Creeks Golf Club", "city": "Stanton", "region": "Northeast", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 439-2282", "website": "", "description": "A welcoming semi-private club in Stanton with a scenic layout and a tight-knit membership community.", "photo": "", "social_facebook": "", "slug": "twin-creeks-golf-club"},
  {"name": "Wayne Country Club", "city": "Wayne", "region": "Northeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 375-1505", "website": "", "description": "Wayne's semi-private 9-hole club, conveniently located near Wayne State College and well-maintained throughout the season.", "photo": "", "social_facebook": "", "slug": "wayne-country-club"},
  {"name": "Chappell Golf Course", "city": "Chappell", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 874-2581", "website": "", "description": "A wide-open 9-hole public course in Chappell under the big Panhandle sky — affordable golf at the western edge of Nebraska.", "photo": "", "social_facebook": "", "slug": "chappell-golf-course"},
  {"name": "Chimney Rock Golf Club", "city": "Bayard", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 586-2341", "website": "", "description": "A 9-hole public course in Bayard with the iconic Chimney Rock formation visible from the fairways.", "photo": "", "social_facebook": "", "slug": "chimney-rock-golf-club"},
  {"name": "Courthouse and Jail Rock Golf Course", "city": "Bridgeport", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 262-0818", "website": "", "description": "Golf with a geological landmark backdrop — a 9-hole public course in Bridgeport near the famous Courthouse and Jail Rocks.", "photo": "", "social_facebook": "", "slug": "courthouse-and-jail-rock-golf-course"},
  {"name": "Four Winds Golf Course", "city": "Alliance", "region": "Panhandle", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(308) 762-6550", "website": "", "description": "Alliance's 18-hole public course with open Panhandle terrain and reliable, affordable conditions.", "photo": "", "social_facebook": "https://www.facebook.com/FourWindsGolfAlliance/", "slug": "four-winds-golf-course"},
  {"name": "Gordon Golf and Country Club", "city": "Gordon", "region": "Panhandle", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 282-0688", "website": "", "description": "A semi-private 9-hole club in Gordon on the northern edge of the Sandhills — real cowboy country golf.", "photo": "", "social_facebook": "", "slug": "gordon-golf-and-country-club"},
  {"name": "Hillside Golf Course", "city": "Chadron", "region": "Panhandle", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(308) 432-5418", "website": "", "description": "Perched in the Pine Ridge near Chadron State College — an underrated 18-hole public layout with genuine character.", "photo": "", "social_facebook": "", "slug": "hillside-golf-course"},
  {"name": "Legend Buttes Golf Course", "city": "Rushville", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 327-2513", "website": "", "description": "A remote 9-hole public course in Rushville with vast Panhandle views and a genuinely off-the-beaten-path feel.", "photo": "", "social_facebook": "", "slug": "legend-buttes-golf-course"},
  {"name": "Monument Shadows Golf Course", "city": "Gering", "region": "Panhandle", "club_type": "Public", "holes": "18", "greens_fee": "$25–$40", "phone": "(308) 436-3850", "website": "", "description": "Tee off with Scotts Bluff National Monument looming in the background — one of Nebraska's most visually dramatic golf settings.", "photo": "", "social_facebook": "https://www.facebook.com/MonumentShadowsGolf/", "slug": "monument-shadows-golf-course"},
  {"name": "Oshkosh Country Club", "city": "Oshkosh", "region": "Panhandle", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 772-3660", "website": "", "description": "A 9-hole semi-private course in Oshkosh in the heart of Garden County — quiet, affordable, and authentic.", "photo": "", "social_facebook": "", "slug": "oshkosh-country-club"},
  {"name": "Pelican Beach Golf Course", "city": "Brule", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 287-2560", "website": "", "description": "A 9-hole public course near Brule on the shores of Lake McConaughy — one of Nebraska's most scenic golfing backdrops.", "photo": "", "social_facebook": "", "slug": "pelican-beach-golf-course"},
  {"name": "Ridgeview Country Club", "city": "Mitchell", "region": "Panhandle", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 623-1313", "website": "", "description": "Mitchell's semi-private 9-hole country club with North Platte River valley views and a friendly atmosphere.", "photo": "", "social_facebook": "", "slug": "ridgeview-country-club"},
  {"name": "Riverview Golf and Country Club", "city": "Scottsbluff", "region": "Panhandle", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$22–$35", "phone": "(308) 635-2822", "website": "", "description": "Scottsbluff's established semi-private club with a mature 18-hole layout and scenic North Platte River setting.", "photo": "", "social_facebook": "", "slug": "riverview-golf-and-country-club"},
  {"name": "Rolling Green Golf Course", "city": "Morrill", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 247-2303", "website": "", "description": "A relaxed 9-hole public course in Morrill offering affordable golf in the North Platte River valley.", "photo": "", "social_facebook": "", "slug": "rolling-green-golf-course"},
  {"name": "Sand Ridge Golf Course", "city": "Scottsbluff", "region": "Panhandle", "club_type": "Public", "holes": "18", "greens_fee": "$18–$30", "phone": "(308) 630-6639", "website": "", "description": "The Panhandle's top public daily-fee course with the dramatic backdrop of Scotts Bluff National Monument.", "photo": "", "social_facebook": "https://www.facebook.com/SandRidgeGolfScottsbluff/", "slug": "sand-ridge-golf-course"},
  {"name": "Scenic Knolls Golf Course", "city": "Crawford", "region": "Panhandle", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 665-1565", "website": "", "description": "Crawford's 9-hole public course near Fort Robinson State Park — dramatic Pine Ridge terrain and big sky views.", "photo": "", "social_facebook": "", "slug": "scenic-knolls-golf-course"},
  {"name": "Scotts Bluff Country Club", "city": "Scottsbluff", "region": "Panhandle", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 632-3451", "website": "", "description": "The Panhandle's premier private club with a classic layout and a long history as the social center of western Nebraska golf.", "photo": "", "social_facebook": "", "slug": "scotts-bluff-country-club"},
  {"name": "Sky View Golf Course", "city": "Sidney", "region": "Panhandle", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(308) 254-2219", "website": "", "description": "Sidney's public 18-hole course with big Panhandle sky views and a friendly layout for all skill levels.", "photo": "", "social_facebook": "https://www.facebook.com/SkyViewGolfSidney/", "slug": "sky-view-golf-course"},
  {"name": "Ainsworth Golf Course", "city": "Ainsworth", "region": "Sandhills", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 387-2844", "website": "", "description": "A 9-hole public course in Ainsworth offering a peaceful round on the Sandhills' eastern edge.", "photo": "", "social_facebook": "", "slug": "ainsworth-golf-course"},
  {"name": "Arnold Golf Course", "city": "Arnold", "region": "Sandhills", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 848-2346", "website": "", "description": "Arnold's community 9-hole course — a quintessential Sandhills small-town golf experience.", "photo": "", "social_facebook": "", "slug": "arnold-golf-course"},
  {"name": "Bayside Golf Course", "city": "Valentine", "region": "Sandhills", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(402) 376-3145", "website": "", "description": "A public 18-hole course in Valentine surrounded by the natural beauty of the Sandhills — great value in an iconic setting.", "photo": "", "social_facebook": "", "slug": "bayside-golf-course"},
  {"name": "Broken Bow Country Club", "city": "Broken Bow", "region": "Sandhills", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$18–$28", "phone": "(308) 872-2694", "website": "", "description": "The Sandhills' friendliest semi-private track — a genuine small-town golf experience with natural terrain and wide-open sky.", "photo": "", "social_facebook": "https://www.facebook.com/BrokenBowCountryClub/", "slug": "broken-bow-country-club"},
  {"name": "CapRock Ranch", "city": "Hyannis", "region": "Sandhills", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 458-2222", "website": "", "description": "An exclusive Sandhills private club delivering raw, rugged golf in one of Nebraska's most remote and beautiful settings.", "photo": "", "social_facebook": "", "slug": "caprock-ranch"},
  {"name": "Dismal River Club", "city": "Mullen", "region": "Sandhills", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 546-2485", "website": "https://www.dismalriver.com/", "description": "Tom Doak's raw, rugged Sandhills layout — 18 holes of pure links golf where the wind is always a factor and the views stretch forever.", "photo": "", "social_facebook": "", "slug": "dismal-river-club"},
  {"name": "Frederick Peak Golf Club", "city": "Valentine", "region": "Sandhills", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 376-1225", "website": "", "description": "Valentine's 9-hole semi-private course with panoramic Sandhills views — a relaxed round in a spectacular setting.", "photo": "", "social_facebook": "", "slug": "frederick-peak-golf-club"},
  {"name": "GrayBull", "city": "Hyannis", "region": "Sandhills", "club_type": "Private", "holes": "18", "greens_fee": "$200–$350", "phone": "(402) 817-3673", "website": "https://dormie.network/courses/graybull", "description": "Gil Hanse's links masterpiece in the Nebraska Sandhills — dramatic, minimalist, and utterly unforgettable. One of the newest gems in the region.", "photo": "", "social_facebook": "https://www.facebook.com/DormieNetwork/", "slug": "graybull"},
  {"name": "Mullen Golf Club", "city": "Mullen", "region": "Sandhills", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 546-2331", "website": "", "description": "A 9-hole public course in the heart of Mullen, gateway to the Sandhills golf corridor. Simple, authentic, and affordable.", "photo": "", "social_facebook": "", "slug": "mullen-golf-club"},
  {"name": "Sand Hills Golf Club", "city": "Mullen", "region": "Sandhills", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 546-2437", "website": "", "description": "Routinely ranked among the top 10 courses in the world, Sand Hills is a pure, walking-only links carved from Nebraska's rolling Sandhills. A pilgrimage for serious golfers.", "photo": "https://www.nebgolf.org/wp-content/uploads/2019/02/2013-05-23_1369327642.jpg", "social_facebook": "", "slug": "sand-hills-golf-club"},
  {"name": "The Prairie Club", "city": "Valentine", "region": "Sandhills", "club_type": "Private", "holes": "36", "greens_fee": "$150–$350", "phone": "(402) 376-2022", "website": "https://www.theprairieclub.com/", "description": "Two full 18-hole courses — The Dunes and The Pines — built into Nebraska's most stunning Sandhills terrain. A bucket-list destination.", "photo": "", "social_facebook": "https://www.facebook.com/ThePrairieClub/", "slug": "the-prairie-club"},
  {"name": "Alma Golf Course", "city": "Alma", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 928-2026", "website": "", "description": "A 9-hole public course in Alma near Harlan County Reservoir — a pleasant round in Southwest Nebraska's lake country.", "photo": "", "social_facebook": "", "slug": "alma-golf-course"},
  {"name": "Arapahoe Golf Course", "city": "Arapahoe", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 962-5396", "website": "", "description": "A friendly 9-hole public course in Arapahoe serving the Furnas County golf community.", "photo": "", "social_facebook": "", "slug": "arapahoe-golf-course"},
  {"name": "Awarii Dunes Golf Club", "city": "Axtell", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$30–$50", "phone": "(308) 743-5938", "website": "https://www.awaridunes.com/", "description": "Nebraska's most acclaimed public Sandhills-style course — wide open, wind-swept, and absolutely addicting. Worth the drive from anywhere in the state.", "photo": "", "social_facebook": "https://www.facebook.com/AwariiDunes/", "slug": "awarii-dunes-golf-club"},
  {"name": "Buffalo Ridge Golf Course", "city": "Kearney", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$25–$40", "phone": "(308) 338-8303", "website": "", "description": "Kearney's top public daily-fee course with wide fairways and excellent conditioning year-round.", "photo": "", "social_facebook": "https://www.facebook.com/BuffaloRidgeGolf/", "slug": "buffalo-ridge-golf-course"},
  {"name": "Centura Hills Golf Club", "city": "Cairo", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(308) 485-4611", "website": "", "description": "Central Nebraska's underrated gem — a surprisingly challenging public layout in Cairo with a loyal following.", "photo": "", "social_facebook": "", "slug": "centura-hills-golf-club"},
  {"name": "Crooked Creek Country Club", "city": "Pleasanton", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 388-4466", "website": "", "description": "A semi-private 9-hole layout in Pleasanton along Crooked Creek — natural surroundings and relaxed small-town atmosphere.", "photo": "", "social_facebook": "", "slug": "crooked-creek-country-club"},
  {"name": "Elks Country Golf - Kearney", "city": "Kearney", "region": "South Central", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$25–$38", "phone": "(308) 234-3430", "website": "", "description": "A well-established Kearney semi-private track with a loyal membership and a quality 18-hole layout.", "photo": "", "social_facebook": "", "slug": "elks-country-golf---kearney"},
  {"name": "Elks Golf Course - Hastings", "city": "Hastings", "region": "South Central", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 463-2887", "website": "", "description": "A classic Hastings semi-private track with decades of history and a layout that rewards consistent ball-striking.", "photo": "", "social_facebook": "", "slug": "elks-golf-course---hastings"},
  {"name": "Fonner View Golf Course", "city": "Grand Island", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(308) 385-5340", "website": "", "description": "Grand Island's public 9-hole course at the Fonner Park fairgrounds, with a straightforward layout and easy access.", "photo": "", "social_facebook": "", "slug": "fonner-view-golf-course"},
  {"name": "Fox Hollow Golf Course", "city": "Grand Island", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$22–$38", "phone": "(308) 385-5810", "website": "", "description": "Grand Island's best public course with a well-balanced mix of risk-reward holes and excellent conditioning.", "photo": "", "social_facebook": "https://www.facebook.com/FoxHollowGrandIsland/", "slug": "fox-hollow-golf-course"},
  {"name": "Franklin Country Club", "city": "Franklin", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 425-6288", "website": "", "description": "A 9-hole semi-private course in Franklin — a classic small-town country club in South Central Nebraska.", "photo": "", "social_facebook": "", "slug": "franklin-country-club"},
  {"name": "Galaway Creek Golf Course", "city": "Hastings", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$22–$38", "phone": "(402) 461-4653", "website": "", "description": "Hastings' top public layout with creek-side holes and consistent conditioning throughout the season.", "photo": "", "social_facebook": "", "slug": "galaway-creek-golf-course"},
  {"name": "Gibbon Valley View Golf Club", "city": "Gibbon", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 468-5557", "website": "", "description": "A 9-hole public course in Gibbon with Platte River valley views and an easygoing pace of play.", "photo": "", "social_facebook": "", "slug": "gibbon-valley-view-golf-club"},
  {"name": "Holdrege Country Club", "city": "Holdrege", "region": "South Central", "club_type": "Semi-Private", "holes": "18", "greens_fee": "$22–$35", "phone": "(308) 995-5861", "website": "", "description": "A well-respected South Central semi-private club with tree-lined fairways and a challenging but fair layout.", "photo": "", "social_facebook": "", "slug": "holdrege-country-club"},
  {"name": "Indianhead Golf Club", "city": "Grand Island", "region": "South Central", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 382-6404", "website": "", "description": "Grand Island's prestigious private 18-hole club — one of South Central Nebraska's premier golf experiences.", "photo": "", "social_facebook": "", "slug": "indianhead-golf-club"},
  {"name": "Jackrabbit Run Golf Course", "city": "Aurora", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 694-3449", "website": "", "description": "Central Nebraska's most playful public layout — fast greens, creative holes, and outstanding value near Aurora.", "photo": "", "social_facebook": "https://www.facebook.com/JackrabbitRunGolf/", "slug": "jackrabbit-run-golf-course"},
  {"name": "Kearney Country Club", "city": "Kearney", "region": "South Central", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 237-5171", "website": "", "description": "Kearney's private club with a championship layout and a distinguished membership history in central Nebraska.", "photo": "", "social_facebook": "", "slug": "kearney-country-club"},
  {"name": "Lochland Country Club", "city": "Hastings", "region": "South Central", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 463-3494", "website": "", "description": "Hastings' private golf club with a well-regarded 18-hole layout and active membership program.", "photo": "", "social_facebook": "", "slug": "lochland-country-club"},
  {"name": "Loup City Golf Club", "city": "Loup City", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 745-0535", "website": "", "description": "A 9-hole public course in Loup City near Sherman Reservoir — peaceful, affordable, and genuinely off the beaten path.", "photo": "", "social_facebook": "", "slug": "loup-city-golf-club"},
  {"name": "Meadowlark Hills Golf Course", "city": "Kearney", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(308) 234-9238", "website": "", "description": "A public 9-hole layout in Kearney offering a relaxed round near the Platte River with affordable fees.", "photo": "", "social_facebook": "", "slug": "meadowlark-hills-golf-course"},
  {"name": "Minden Country Club", "city": "Minden", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 832-2363", "website": "", "description": "A welcoming 9-hole semi-private club in Minden serving the Kearney County golf community.", "photo": "", "social_facebook": "", "slug": "minden-country-club"},
  {"name": "Pawnee Hills Golf Club", "city": "Henderson", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(402) 723-5241", "website": "", "description": "A public course in Henderson offering a comfortable round with well-maintained greens and friendly service.", "photo": "", "social_facebook": "", "slug": "pawnee-hills-golf-club"},
  {"name": "Poco Creek Golf Course", "city": "Marquette", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 854-3444", "website": "", "description": "A peaceful 9-hole public course in Marquette following Poco Creek through central Hamilton County.", "photo": "", "social_facebook": "", "slug": "poco-creek-golf-course"},
  {"name": "Ravenna Golf Club", "city": "Ravenna", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 452-3455", "website": "", "description": "A 9-hole public course in Ravenna with a relaxed atmosphere and well-maintained greens.", "photo": "", "social_facebook": "", "slug": "ravenna-golf-club"},
  {"name": "Red Cloud Golf Club", "city": "Red Cloud", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 746-3671", "website": "", "description": "A 9-hole public course in Red Cloud — the town made famous by Willa Cather — with a charming small-town character.", "photo": "", "social_facebook": "", "slug": "red-cloud-golf-club"},
  {"name": "Riverside Golf Club", "city": "Osceola", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 747-2540", "website": "", "description": "A 9-hole semi-private layout in Osceola along the Beaver Creek corridor, well-suited for relaxed community golf.", "photo": "", "social_facebook": "", "slug": "riverside-golf-club"},
  {"name": "Ryan Hill Country Club", "city": "Sutton", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 773-4441", "website": "", "description": "Sutton's 9-hole semi-private club with a laid-back atmosphere and consistent conditioning.", "photo": "", "social_facebook": "", "slug": "ryan-hill-country-club"},
  {"name": "Southern Hills Golf Course", "city": "Hastings", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$20–$34", "phone": "(402) 463-0103", "website": "", "description": "Hastings' most accessible daily-fee course with a welcoming atmosphere and a solid 18-hole layout.", "photo": "", "social_facebook": "", "slug": "southern-hills-golf-course"},
  {"name": "St Paul Country Club", "city": "St. Paul", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 754-4433", "website": "", "description": "A 9-hole semi-private layout in St. Paul serving the Howard County community with affordable golf.", "photo": "", "social_facebook": "", "slug": "st-paul-country-club"},
  {"name": "Superior Country Club", "city": "Superior", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 879-4420", "website": "", "description": "A 9-hole semi-private course in Superior near the Kansas line — well-kept and community-focused.", "photo": "", "social_facebook": "", "slug": "superior-country-club"},
  {"name": "The Greens at Prairie Hills", "city": "Sutton", "region": "South Central", "club_type": "Public", "holes": "18", "greens_fee": "$22–$35", "phone": "(402) 773-5500", "website": "", "description": "A quality public layout in Sutton with open prairie views and a challenging but accessible design.", "photo": "", "social_facebook": "", "slug": "the-greens-at-prairie-hills"},
  {"name": "Valley View Country Club", "city": "Clay Center", "region": "South Central", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 762-3413", "website": "", "description": "A 9-hole semi-private layout in Clay Center with valley views and a friendly, welcoming membership.", "photo": "", "social_facebook": "", "slug": "valley-view-country-club"},
  {"name": "Wood River Golf Course", "city": "Wood River", "region": "South Central", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 583-2278", "website": "", "description": "A relaxed 9-hole public course in Wood River alongside the Platte River — a solid value for casual golfers.", "photo": "", "social_facebook": "", "slug": "wood-river-golf-course"},
  {"name": "York Country Club", "city": "York", "region": "South Central", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 362-5547", "website": "", "description": "York's private 18-hole club with a well-regarded layout and a long history as a hub of south-central Nebraska golf.", "photo": "", "social_facebook": "", "slug": "york-country-club"},
  {"name": "ArborLinks", "city": "Nebraska City", "region": "Southeast", "club_type": "Public", "holes": "18", "greens_fee": "$35–$55", "phone": "(402) 873-4653", "website": "https://www.arborlinks.com/", "description": "Carved through Arbor Day Farm's rolling orchards and forest, ArborLinks is one of Nebraska's most scenic and unique public courses.", "photo": "https://www.nebgolf.org/wp-content/uploads/2019/02/ArborLinks-1000x660.jpg", "social_facebook": "https://www.facebook.com/ArborLinksGolf/", "slug": "arborlinks"},
  {"name": "Auburn Country Club", "city": "Auburn", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 274-3581", "website": "", "description": "A 9-hole semi-private course in Auburn with a classic southeast Nebraska layout and welcoming membership.", "photo": "", "social_facebook": "", "slug": "auburn-country-club"},
  {"name": "Beatrice Country Club", "city": "Beatrice", "region": "Southeast", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(402) 228-3939", "website": "", "description": "Beatrice's private 18-hole club with a tree-lined layout and a rich history in southeast Nebraska golf.", "photo": "", "social_facebook": "", "slug": "beatrice-country-club"},
  {"name": "College Heights Country Club", "city": "Crete", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$14–$22", "phone": "(402) 826-2232", "website": "", "description": "A 9-hole semi-private course near Doane University in Crete with a relaxed collegiate-town atmosphere.", "photo": "", "social_facebook": "", "slug": "college-heights-country-club"},
  {"name": "Fairbury Country Club", "city": "Fairbury", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 729-3347", "website": "", "description": "A solid 9-hole semi-private layout in Fairbury serving the Jefferson County golf community.", "photo": "", "social_facebook": "", "slug": "fairbury-country-club"},
  {"name": "Falls City Golf Course", "city": "Falls City", "region": "Southeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 245-4416", "website": "", "description": "Falls City's public 9-hole course in the far southeast corner of Nebraska — genuine small-town Americana golf.", "photo": "", "social_facebook": "", "slug": "falls-city-golf-course"},
  {"name": "Friend Country Club", "city": "Friend", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 947-2940", "website": "", "description": "A 9-hole semi-private layout in Friend with rolling terrain and a loyal local membership.", "photo": "", "social_facebook": "", "slug": "friend-country-club"},
  {"name": "Hebron Country Club", "city": "Hebron", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 768-7171", "website": "", "description": "A well-maintained 9-hole semi-private course in Hebron near the Kansas border.", "photo": "", "social_facebook": "", "slug": "hebron-country-club"},
  {"name": "Hidden Acres Golf Club", "city": "Syracuse", "region": "Southeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 269-2581", "website": "", "description": "A 9-hole public course tucked into the hills near Syracuse with a peaceful, natural setting.", "photo": "", "social_facebook": "", "slug": "hidden-acres-golf-club"},
  {"name": "Hidden Hills Country Club", "city": "Humboldt", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 862-2340", "website": "", "description": "A 9-hole semi-private course in Humboldt on the rolling hills of southeast Nebraska.", "photo": "", "social_facebook": "", "slug": "hidden-hills-country-club"},
  {"name": "Kirkman's Lakeview Golf Course", "city": "Johnson Lake", "region": "Southeast", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(308) 762-6550", "website": "", "description": "A scenic 18-hole public course on Johnson Lake offering water views and a pleasant resort-style atmosphere.", "photo": "", "social_facebook": "", "slug": "kirkmans-lakeview-golf-course"},
  {"name": "Syracuse Country Club", "city": "Syracuse", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 269-3355", "website": "", "description": "A 9-hole semi-private layout in Syracuse with a long community history and consistent conditions.", "photo": "", "social_facebook": "", "slug": "syracuse-country-club"},
  {"name": "Tecumseh Country Club", "city": "Tecumseh", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(402) 335-2851", "website": "", "description": "A 9-hole semi-private course in Tecumseh with a classic country club feel in southeast Nebraska.", "photo": "", "social_facebook": "", "slug": "tecumseh-country-club"},
  {"name": "The Golf Club at Table Creek", "city": "Nebraska City", "region": "Southeast", "club_type": "Public", "holes": "18", "greens_fee": "$30–$50", "phone": "(402) 873-7662", "website": "", "description": "A scenic daily-fee course near Nebraska City with dramatic elevation changes and sweeping Missouri River valley views.", "photo": "", "social_facebook": "https://www.facebook.com/TableCreekGolf/", "slug": "the-golf-club-at-table-creek"},
  {"name": "Thornridge Golf Course", "city": "Plattsmouth", "region": "Southeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 296-3131", "website": "", "description": "A public 9-hole layout in Plattsmouth near the Missouri River — an affordable option for Sarpy County golfers.", "photo": "", "social_facebook": "", "slug": "thornridge-golf-course"},
  {"name": "Wildwood Golf Course", "city": "Ashland", "region": "Southeast", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 944-2424", "website": "", "description": "A casual 9-hole public course in Ashland, a quick round before or after a visit to Mahoney State Park.", "photo": "", "social_facebook": "", "slug": "wildwood-golf-course"},
  {"name": "Wymore Country Club", "city": "Wymore", "region": "Southeast", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(402) 645-3537", "website": "", "description": "Wymore's 9-hole semi-private community club near the Kansas border — friendly, affordable, and well-kept.", "photo": "", "social_facebook": "", "slug": "wymore-country-club"},
  {"name": "Arrowhead Meadows Golf Course", "city": "North Platte", "region": "Southwest", "club_type": "Public", "holes": "9", "greens_fee": "$14–$22", "phone": "(308) 532-7299", "website": "", "description": "A 9-hole public course in North Platte offering an affordable warm-up round or a relaxed evening nine.", "photo": "", "social_facebook": "", "slug": "arrowhead-meadows-golf-course"},
  {"name": "Benkelman Country Club", "city": "Benkelman", "region": "Southwest", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 423-2494", "website": "", "description": "A semi-private 9-hole course in Benkelman at the southwest corner of Nebraska — as off-the-beaten-path as it gets.", "photo": "", "social_facebook": "", "slug": "benkelman-country-club"},
  {"name": "Cardinal Country Club", "city": "Ogallala", "region": "Southwest", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 284-4085", "website": "", "description": "Ogallala's semi-private 9-hole club near Lake McConaughy — a relaxed round in Nebraska's lake country.", "photo": "", "social_facebook": "", "slug": "cardinal-country-club"},
  {"name": "Cozad Country Club", "city": "Cozad", "region": "Southwest", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 784-2726", "website": "", "description": "A 9-hole semi-private layout in Cozad on the 100th meridian — the geographic heart of the United States.", "photo": "", "social_facebook": "", "slug": "cozad-country-club"},
  {"name": "Crandall Creek Golf Club", "city": "North Platte", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(308) 532-1234", "website": "", "description": "North Platte's most accessible daily-fee course — great for all skill levels with open fairways and a relaxed atmosphere.", "photo": "", "social_facebook": "", "slug": "crandall-creek-golf-club"},
  {"name": "Cross Creek Golf Links", "city": "McCook", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(308) 345-3533", "website": "", "description": "A friendly daily-fee course in McCook delivering straightforward, enjoyable golf at a very fair price.", "photo": "", "social_facebook": "https://www.facebook.com/CrossCreekGolfLinks/", "slug": "cross-creek-golf-links"},
  {"name": "Enders Lake Golf Course", "city": "Enders", "region": "Southwest", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 882-4384", "website": "", "description": "A scenic 9-hole public course near Enders Reservoir — peaceful southwest Nebraska golf with lake views.", "photo": "", "social_facebook": "", "slug": "enders-lake-golf-course"},
  {"name": "Heritage Hills Golf Course", "city": "McCook", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(308) 345-5032", "website": "", "description": "McCook's signature public course set into the rolling Republican River valley with scenic elevation changes.", "photo": "", "social_facebook": "https://www.facebook.com/HeritageHillsGolfMcCook/", "slug": "heritage-hills-golf-course"},
  {"name": "Hi-Line Golf Course", "city": "Kimball", "region": "Southwest", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 235-4963", "website": "", "description": "A 9-hole public course in Kimball at Nebraska's western edge, near the Wyoming border — big sky, simple golf.", "photo": "", "social_facebook": "", "slug": "hi-line-golf-course"},
  {"name": "Imperial Country Club", "city": "Imperial", "region": "Southwest", "club_type": "Semi-Private", "holes": "9", "greens_fee": "$12–$20", "phone": "(308) 882-5441", "website": "", "description": "A semi-private 9-hole layout in Imperial serving the Chase County golf community in southwest Nebraska.", "photo": "", "social_facebook": "", "slug": "imperial-country-club"},
  {"name": "Lake Maloney Golf Club", "city": "North Platte", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$20–$32", "phone": "(308) 532-6684", "website": "", "description": "A pleasant daily-fee layout adjacent to Lake Maloney with solid conditioning and affordable fees.", "photo": "", "social_facebook": "https://www.facebook.com/LakeMaloneyGolf/", "slug": "lake-maloney-golf-club"},
  {"name": "Lakeside Golf Club", "city": "Ogallala", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$20–$34", "phone": "(308) 284-8989", "website": "", "description": "Ogallala's 18-hole public course with lake views and a pleasant round for golfers passing through the western Platte Valley.", "photo": "", "social_facebook": "", "slug": "lakeside-golf-club"},
  {"name": "Oregon Trail Golf Course", "city": "Gothenburg", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$18–$28", "phone": "(308) 537-7700", "website": "", "description": "A solid public layout in Gothenburg following the historic Oregon Trail corridor through Nebraska's Platte Valley.", "photo": "", "social_facebook": "https://www.facebook.com/OregonTrailGolfGothenburg/", "slug": "oregon-trail-golf-course"},
  {"name": "Overton Golf Club", "city": "Overton", "region": "Southwest", "club_type": "Public", "holes": "9", "greens_fee": "$10–$18", "phone": "(308) 987-2460", "website": "", "description": "Overton's 9-hole public course along the Platte River — a straightforward, affordable round in rural Nebraska.", "photo": "", "social_facebook": "", "slug": "overton-golf-club"},
  {"name": "Pheasant Run Golf Club", "city": "North Platte", "region": "Southwest", "club_type": "Private", "holes": "18", "greens_fee": "Members only", "phone": "(308) 532-2280", "website": "", "description": "North Platte's private 18-hole club with well-maintained conditions and an exclusive membership experience.", "photo": "", "social_facebook": "", "slug": "pheasant-run-golf-club"},
  {"name": "Rivers Edge Golf Club", "city": "North Platte", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$22–$36", "phone": "(308) 532-7299", "website": "", "description": "North Platte's top public course with a scenic Platte River setting and challenging, well-conditioned holes.", "photo": "", "social_facebook": "https://www.facebook.com/RiversEdgeGolfNorthPlatte/", "slug": "rivers-edge-golf-club"},
  {"name": "Wild Horse Golf Club", "city": "Gothenburg", "region": "Southwest", "club_type": "Public", "holes": "18", "greens_fee": "$35–$55", "phone": "(308) 537-7700", "website": "http://www.wildhorsegolf.com/", "description": "A wind-swept prairie links in the heart of Nebraska. Playful, imaginative design with natural Sandhills turf — a hidden gem worth the drive.", "photo": "", "social_facebook": "https://www.facebook.com/WildHorseGolfClub/", "slug": "wild-horse-golf-club"}
];

const REGION_EMOJI = {
  "Sandhills":     "🌾",
  "East":          "🏙️",
  "Panhandle":     "🏔️",
  "Northeast":     "🌊",
  "South Central": "🌻",
  "Southwest":     "🌵",
  "Southeast":     "🌳",
  "North Central": "🦅",
};

function getDayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function buildPostText(course, courseUrl) {
  const emoji = REGION_EMOJI[course.region] || "⛳";
  const typeLabel = course.club_type === "Public" ? "Public" : course.club_type;
  const holesText = course.holes ? `${course.holes}-hole` : "";
  const feeText = course.greens_fee && course.greens_fee !== "Members only"
    ? `\n💰 Greens fee: ${course.greens_fee}` : "";
  const phoneText = course.phone ? `\n📞 ${course.phone}` : "";
  const websiteText = course.website ? `\n🌐 ${course.website}` : "";
  const regionTag = course.region.replace(/\s+/g, "");

  return `${emoji} Course of the Day: ${course.name}

📍 ${course.city}, Nebraska · ${course.region} Region
⛳ ${holesText} ${typeLabel} Course${feeText}${phoneText}${websiteText}

${course.description}

🔗 Full details & map: ${courseUrl}

#NebraskaGolf #Golf #Nebraska #${regionTag}Golf #LoveNebraskaGolf`;
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET");
  res.setHeader("Cache-Control", "public, max-age=3600"); // cache 1 hour

  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const siteUrl = process.env.SITE_URL || "https://lovenebraskagolf.com";
    const now = new Date();

    // Allow ?date=YYYY-MM-DD to preview a specific day
    let targetDate = now;
    if (req.query.date) {
      targetDate = new Date(req.query.date + "T12:00:00Z");
    }

    // Allow ?preview=N to see next N days
    const previewCount = parseInt(req.query.preview) || 0;

    if (previewCount > 0 && previewCount <= 30) {
      const preview = [];
      for (let i = 0; i < previewCount; i++) {
        const d = new Date(targetDate);
        d.setDate(d.getDate() + i);
        const day = getDayOfYear(d);
        const course = COURSES[day % COURSES.length];
        const courseUrl = `${siteUrl}/?course=${slugify(course.name)}`;
        preview.push({
          date: d.toISOString().split("T")[0],
          day_number: day,
          name: course.name,
          city: course.city,
          region: course.region,
          post_text: buildPostText(course, courseUrl),
          photo: course.photo || "",
          course_url: courseUrl,
        });
      }
      return res.status(200).json({
        generated_at: now.toISOString(),
        count: preview.length,
        preview,
      });
    }

    // Return today's featured course
    const dayNumber = getDayOfYear(targetDate);
    const course = COURSES[dayNumber % COURSES.length];
    const courseUrl = `${siteUrl}/?course=${slugify(course.name)}`;
    const postText = buildPostText(course, courseUrl);

    return res.status(200).json({
      generated_at: now.toISOString(),
      date: targetDate.toISOString().split("T")[0],
      day_number: dayNumber,
      name: course.name,
      city: course.city,
      region: course.region,
      club_type: course.club_type,
      holes: course.holes,
      greens_fee: course.greens_fee || "",
      phone: course.phone || "",
      website: course.website || "",
      description: course.description || "",
      photo: course.photo || "",
      course_url: courseUrl,
      facebook_page: course.social_facebook || "",
      post_text: postText,
      hashtags: `#NebraskaGolf #Golf #Nebraska #${course.region.replace(/\s+/g,"")}Golf #LoveNebraskaGolf`,
    });

  } catch (err) {
    console.error("daily-course error:", err.message);
    return res.status(500).json({ error: err.message });
  }
}
